version: "3.3"

services:
  postgres:
    restart: always
    container_name: "postgres"
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=delivery
    ports:
      - "5432:5432"
